version: '3.1'
services:
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=haydikodlayalim
      - RABBITMQ_DEFAULT_PASS=1234

